import re
import datetime
from pathlib import Path
from typing import List, Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Flowable, Preformatted, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader

# --- Heading Marker Flowable ---
class HeadingMarker(Flowable):
    """
    A dummy flowable inserted before H1 headings. When drawn during the page layout,
    it records the page number of the heading on the canvas.
    """
    def __init__(self, heading_title: str):
        super().__init__()
        self.heading_title = heading_title

    def draw(self):
        # self.canv is the active ReportLab Canvas
        if hasattr(self.canv, 'recorded_headings'):
            self.canv.recorded_headings[self.heading_title] = self.canv._pageNumber

# --- Numbered Canvas Factory ---
def make_canvas_class(headings_dict: dict):
    """
    Creates a dynamic NumberedCanvas class type scoped to a single request
    to isolate heading tracking and multi-page calculation.
    """
    class RequestNumberedCanvas(canvas.Canvas):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self._saved_page_states = []
            self.recorded_headings = headings_dict

        def showPage(self):
            # Save the current canvas state for the final drawing pass
            self._saved_page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            num_pages = len(self._saved_page_states)
            # Re-draw the document pages with footer, header, and page numbers
            for state in self._saved_page_states:
                self.__dict__.update(state)
                self.draw_page_elements(num_pages)
                super().showPage()
            super().save()

        def draw_page_elements(self, page_count: int):
            # Page 1 is the cover page (no running headers/footers)
            if self._pageNumber == 1:
                return

            self.saveState()
            
            # --- Fonts & Colors ---
            self.setFont("Helvetica", 9)
            self.setFillColor(colors.HexColor("#475569")) # Slate 600

            # --- Running Header (Pages 3+) ---
            if self._pageNumber > 2:
                self.drawString(54, 756, "CodeSphere AI - Complete Documentation Report")
                self.setStrokeColor(colors.HexColor("#e2e8f0")) # Slate 200
                self.setLineWidth(0.5)
                self.line(54, 750, letter[0] - 54, 750)

            # --- Running Footer (Pages 2+) ---
            footer_text = f"Page {self._pageNumber} of {page_count}"
            self.drawRightString(letter[0] - 54, 36, footer_text)
            self.drawString(54, 36, "Generated by CodeSphere AI")

            # Footer Line
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(54, 48, letter[0] - 54, 48)
            
            self.restoreState()

    return RequestNumberedCanvas

# --- Custom Markdown-to-Flowables Parser ---
class MarkdownPDFParser:
    def __init__(self):
        # Initialize styles
        styles = getSampleStyleSheet()
        
        self.h1_style = ParagraphStyle(
            'ChapterHeading',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=18,
            leading=22,
            textColor=colors.HexColor('#1e3a8a'), # Navy 800
            spaceBefore=18,
            spaceAfter=12,
            keepWithNext=True
        )

        self.h2_style = ParagraphStyle(
            'SubHeading',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=13,
            leading=17,
            textColor=colors.HexColor('#0f172a'), # Slate 900
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True
        )

        self.h3_style = ParagraphStyle(
            'SubSubHeading',
            parent=styles['Normal'],
            fontName='Helvetica-Bold',
            fontSize=10.5,
            leading=14,
            textColor=colors.HexColor('#334155'), # Slate 700
            spaceBefore=10,
            spaceAfter=6,
            keepWithNext=True
        )

        self.body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor('#334155'), # Slate 700
            spaceAfter=8
        )

        self.bullet_style = ParagraphStyle(
            'ReportBullet',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor('#334155'),
            leftIndent=20,
            firstLineIndent=-10,
            spaceAfter=4
        )

        self.number_style = ParagraphStyle(
            'ReportNumber',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=9.5,
            leading=14.5,
            textColor=colors.HexColor('#334155'),
            leftIndent=20,
            firstLineIndent=-10,
            spaceAfter=4
        )

        self.code_style = ParagraphStyle(
            'ReportCodeBlock',
            parent=styles['Normal'],
            fontName='Courier',
            fontSize=8.5,
            leading=11,
            textColor=colors.HexColor('#0f172a'),
            backColor=colors.HexColor('#f8fafc'),
            borderColor=colors.HexColor('#cbd5e1'),
            borderWidth=0.5,
            borderPadding=8,
            spaceBefore=6,
            spaceAfter=6,
            keepWithNext=True
        )

    def format_inline(self, text: str) -> str:
        """
        Escapes HTML syntax and replaces basic markdown styling (bold, italic, inline code, links)
        with HTML-like markup compatible with ReportLab's Paragraph parser.
        """
        if not text:
            return ""
        
        # 1. Escape basic HTML entities (order is important!)
        text = text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        
        # Extract inline code to protect inner characters
        code_blocks = []
        def repl_code(m):
            code_blocks.append(m.group(1))
            return f"__CODE_{len(code_blocks)-1}__"
            
        text = re.sub(r'`(.*?)`', repl_code, text)
        
        # 2. Bold: **text** or __text__ -> <b>text</b>
        text = re.sub(r'\*\*(.*?)\*\*|__(.*?)__', lambda m: f"<b>{m.group(1) or m.group(2)}</b>", text)
        
        # 3. Italic: *text* or _text_ -> <i>text</i>
        # Using negative lookbehinds/lookaheads to prevent intra-word underscore italics (e.g. snake_case)
        text = re.sub(r'\*(.*?)\*|(?<![A-Za-z0-9])_(.*?)_(?![A-Za-z0-9])', lambda m: f"<i>{m.group(1) or m.group(2)}</i>", text)
        
        # 4. Links: [label](url)
        def repl_link(m):
            label = m.group(1)
            url = m.group(2)
            if url.startswith('http://') or url.startswith('https://'):
                return f'<a href="{url}"><font color="#2563eb">{label}</font></a>'
            elif url.startswith('#'):
                return f'<b>{label}</b>'
            else:
                return f'<b>{label}</b> ({url})'
                
        text = re.sub(r'\[(.*?)\]\((.*?)\)', repl_link, text)
        
        # Restore inline code blocks
        for i, code in enumerate(code_blocks):
            text = text.replace(f"__CODE_{i}__", f'<font name="Courier" size="8.5" color="#0f172a"><b>{code}</b></font>')
            
        return text

    def parse_markdown_table(self, table_lines: List[str]) -> Table:
        """Parses markdown table lines into a styled ReportLab Table."""
        rows = []
        for line in table_lines:
            line_stripped = line.strip()
            if not line_stripped:
                continue
            
            cells = [c.strip() for c in line_stripped.split('|')]
            if len(cells) >= 2:
                # Discard outer empty cells resulting from leading/trailing pipe symbols
                if cells[0] == "":
                    cells = cells[1:]
                if cells and cells[-1] == "":
                    cells = cells[:-1]
                rows.append(cells)
                
        if not rows:
            return None

        # Check for separator row (like |---|---|)
        has_separator = False
        if len(rows) > 1:
            second_row = rows[1]
            if all(re.match(r'^:?-+:?$', cell) for cell in second_row):
                has_separator = True

        if has_separator:
            headers = rows[0]
            data_rows = rows[2:]
        else:
            headers = None
            data_rows = rows

        table_data = []
        
        # Format Header
        if headers:
            header_row = []
            for cell in headers:
                header_cell_style = ParagraphStyle(
                    'HeaderCell',
                    parent=self.h3_style,
                    fontSize=9,
                    textColor=colors.whitesmoke,
                    spaceBefore=0,
                    spaceAfter=0
                )
                header_row.append(Paragraph(self.format_inline(cell), header_cell_style))
            table_data.append(header_row)

        # Format Data Rows
        for row in data_rows:
            row_data = []
            for cell in row:
                cell_style = ParagraphStyle(
                    'Cell',
                    parent=self.body_style,
                    fontSize=8.5,
                    spaceBefore=0,
                    spaceAfter=0
                )
                row_data.append(Paragraph(self.format_inline(cell), cell_style))
            row_data.extend([Paragraph("", self.body_style)] * (len(headers or [0]) - len(row_data)))
            table_data.append(row_data)

        if not table_data:
            return None

        num_cols = max(len(r) for r in table_data)
        col_widths = [504 / num_cols] * num_cols # 504 is the exact width bounds (612 - 54*2)

        t_style = TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a') if headers else colors.HexColor('#f8fafc')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke if headers else colors.HexColor('#0f172a')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ])

        if headers and len(table_data) > 1:
            t_style.add('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.HexColor('#ffffff'), colors.HexColor('#f8fafc')])
        else:
            t_style.add('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.HexColor('#ffffff'), colors.HexColor('#f8fafc')])

        return Table(table_data, colWidths=col_widths, style=t_style)

    def parse_markdown_image(self, line: str):
        """Attempts to render a standalone markdown image as a ReportLab image flowable."""
        match = re.match(r'^!\[(.*?)\]\((.*?)\)$', line.strip())
        if not match:
            return None

        alt_text, image_ref = match.groups()
        candidate_paths = []
        if image_ref.startswith('http://') or image_ref.startswith('https://') or image_ref.startswith('data:'):
            return Paragraph(f"[Image: {alt_text or image_ref}]", self.body_style)

        raw_path = image_ref.strip().strip('<>')
        candidate_paths.append(Path(raw_path))
        candidate_paths.append(Path.cwd() / raw_path)
        candidate_paths.append(Path(__file__).resolve().parent.parent / raw_path)

        for candidate in candidate_paths:
            if candidate.exists() and candidate.is_file():
                try:
                    return Image(str(candidate), width=300, height=200, kind='proportional')
                except Exception:
                    break

        return Paragraph(f"[Image: {alt_text or image_ref}]", self.body_style)

    def parse(self, md_text: str) -> List[Flowable]:
        """Converts raw markdown text to a sequential list of ReportLab Flowables."""
        flowables = []
        if not md_text:
            return flowables

        lines = md_text.splitlines()
        in_code_block = False
        code_lines = []
        
        in_table = False
        table_lines = []

        i = 0
        while i < len(lines):
            line = lines[i]
            stripped = line.strip()

            # --- Code Blocks ---
            if stripped.startswith("```"):
                if in_code_block:
                    code_text = "\n".join(code_lines)
                    escaped_code = code_text.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
                    flowables.append(Preformatted(escaped_code, self.code_style))
                    code_lines = []
                    in_code_block = False
                else:
                    in_code_block = True
                i += 1
                continue

            if in_code_block:
                code_lines.append(line)
                i += 1
                continue

            # --- Tables ---
            if stripped.startswith("|"):
                in_table = True
                table_lines.append(line)
                i += 1
                continue
            elif in_table:
                # Table ended
                table_flowable = self.parse_markdown_table(table_lines)
                if table_flowable:
                    flowables.append(table_flowable)
                table_lines = []
                in_table = False
                # Do not i += 1 here, let the loop parse the current line (which is not part of the table)

            # --- Markdown Images ---
            if stripped.startswith("!["):
                image_flowable = self.parse_markdown_image(stripped)
                if image_flowable is not None:
                    flowables.append(image_flowable)
                    i += 1
                    continue

            # --- Headings ---
            if stripped.startswith("#"):
                match = re.match(r'^(#{1,6})\s+(.*)$', stripped)
                if match:
                    level = len(match.group(1))
                    title = match.group(2)
                    formatted_title = self.format_inline(title)

                    if level == 1:
                        # H1 acts as a new chapter -> Force Page Break
                        if len(flowables) > 0:
                            flowables.append(PageBreak())
                        flowables.append(HeadingMarker(title))
                        flowables.append(Paragraph(formatted_title, self.h1_style))
                    elif level == 2:
                        flowables.append(Paragraph(formatted_title, self.h2_style))
                    else:
                        flowables.append(Paragraph(formatted_title, self.h3_style))
                i += 1
                continue

            # --- Bullet Lists ---
            if re.match(r'^[*+-]\s+', stripped):
                text = re.sub(r'^[*+-]\s+', '', line)
                flowables.append(Paragraph(f"&bull; {self.format_inline(text)}", self.bullet_style))
                i += 1
                continue

            # --- Numbered Lists ---
            if re.match(r'^\d+\.\s+', stripped):
                text = re.sub(r'^\d+\.\s+', '', line)
                num = re.match(r'^\d+', stripped).group(0)
                flowables.append(Paragraph(f"{num}. {self.format_inline(text)}", self.number_style))
                i += 1
                continue

            # --- Horizontal Rules ---
            if stripped == "---" or stripped == "***":
                flowables.append(Spacer(1, 10))
                flowables.append(Table([['']], colWidths=[504], rowHeights=[1], style=TableStyle([
                    ('LINEABOVE', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
                    ('TOPPADDING', (0,0), (-1,-1), 0),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 0),
                ])))
                flowables.append(Spacer(1, 10))
                i += 1
                continue

            # --- Regular Paragraphs ---
            if stripped:
                flowables.append(Paragraph(self.format_inline(stripped), self.body_style))
            else:
                flowables.append(Spacer(1, 6))

            i += 1

        # Fallback table dump if EOF reached before resetting table state
        if in_table and table_lines:
            table_flowable = self.parse_markdown_table(table_lines)
            if table_flowable:
                flowables.append(table_flowable)

        return flowables

def build_full_report_sections(report: Dict[str, Any]) -> List[Dict[str, str]]:
    """Build a chapter list for the enterprise-quality full documentation report."""
    generated_docs = report.get("generated_docs") or {}
    vulnerabilities = report.get("vulnerabilities") or []
    suggestions = report.get("suggestions") or []
    ai_fixes = report.get("ai_fixes") or []

    def _normalize_content(content: Any, fallback_title: str) -> str:
        if not content:
            return f"# {fallback_title}\n\nNo content was generated for this section."
        if isinstance(content, str):
            return content.strip() if content.strip() else f"# {fallback_title}\n\nNo content was generated for this section."
        return f"# {fallback_title}\n\n{str(content)}"

    summary = (report.get("summary") or "No executive summary generated.").strip()
    repository_name = report.get("project_name") or report.get("repository_name") or report.get("name") or "Unknown Repository"
    project_owner = report.get("project_owner") or report.get("owner_name") or report.get("owner") or "Unknown Owner"
    repository_source = report.get("repository_source") or report.get("source") or "Unknown Source"
    commit_hash = report.get("commit_hash") or report.get("commit") or "N/A"
    quality_metrics = [
        ("Code quality score", report.get("code_quality_score", 0)),
        ("Security score", report.get("security_score", 0)),
        ("Architecture score", report.get("architecture_score", 0)),
        ("Maintainability score", report.get("maintainability_score", 0)),
        ("Documentation score", report.get("documentation_score", 0)),
        ("Testing score", report.get("testing_score", 0)),
        ("Dependency score", report.get("dependency_score", 0)),
        ("Technical debt", report.get("technical_debt", 0)),
        ("Code complexity", report.get("code_complexity", 0)),
    ]

    metrics_lines = ["| Metric | Value |", "| --- | --- |"]
    for metric, value in quality_metrics:
        metrics_lines.append(f"| {metric} | {value} |")

    security_lines = []
    if vulnerabilities:
        for vuln in vulnerabilities:
            severity = vuln.get("severity", "UNKNOWN") if isinstance(vuln, dict) else "UNKNOWN"
            description = vuln.get("description", "No description") if isinstance(vuln, dict) else str(vuln)
            security_lines.append(f"- **{severity}**: {description}")
    else:
        security_lines.append("- No security findings were identified in the latest analysis.")

    recommendation_lines = []
    if suggestions:
        for suggestion in suggestions:
            if isinstance(suggestion, dict):
                rec = suggestion.get("suggestion") or suggestion.get("recommendation") or "Recommendation available"
                explanation = suggestion.get("explanation") or ""
                recommendation_lines.append(f"- **Recommendation**: {rec}")
                if explanation:
                    recommendation_lines.append(f"  - {explanation}")
            else:
                recommendation_lines.append(f"- {suggestion}")
    else:
        recommendation_lines.append("- No AI recommendations were generated.")

    if ai_fixes:
        recommendation_lines.append("\n## Suggested Code Fixes")
        for fix in ai_fixes:
            if isinstance(fix, dict):
                explanation = fix.get("explanation") or "Implementation guidance available"
                recommendation_lines.append(f"- {explanation}")
            else:
                recommendation_lines.append(f"- {fix}")

    sections = [
        {
            "title": "Repository Information",
            "content": "\n".join([
                "# Repository Information",
                "",
                "## Project Details",
                f"- Project Name: {repository_name}",
                f"- Owner: {project_owner}",
                f"- Repository Source: {repository_source}",
                f"- Commit Hash: {commit_hash}",
                f"- Generated At: {datetime.datetime.now().strftime('%B %d, %Y - %H:%M')}",
            ]),
        },
        {
            "title": "Executive Summary",
            "content": "\n".join([
                "# Executive Summary",
                "",
                "## Repository Snapshot",
                "- Repository summary: " + summary,
                "- Generated documentation sections: README, Installation Guide, API Documentation, Developer Guide, Architecture Overview, Folder Structure, Database Documentation, Security Findings, AI Recommendations, Code Quality Metrics, and Knowledge Graph Summary.",
                "",
                "## Executive Highlights",
                "- The repository documentation has been consolidated into a single enterprise-grade report suitable for engineering leadership, security review, and onboarding.",
                "- Each chapter is designed to be self-contained, preserving markdown structure and enabling clean pagination in the PDF export.",
            ]),
        },
        {
            "title": "README",
            "content": _normalize_content(generated_docs.get("readme") or generated_docs.get("README"), "README"),
        },
        {
            "title": "Installation Guide",
            "content": _normalize_content(generated_docs.get("installation") or generated_docs.get("installation_guide"), "Installation Guide"),
        },
        {
            "title": "API Documentation",
            "content": _normalize_content(generated_docs.get("api_docs") or generated_docs.get("apiDocumentation"), "API Documentation"),
        },
        {
            "title": "Developer Guide",
            "content": _normalize_content(generated_docs.get("developer_guide") or generated_docs.get("developerGuide"), "Developer Guide"),
        },
        {
            "title": "Architecture Overview",
            "content": _normalize_content(generated_docs.get("architecture") or generated_docs.get("architecture_overview"), "Architecture Overview"),
        },
        {
            "title": "Folder Structure",
            "content": _normalize_content(generated_docs.get("folder_structure") or generated_docs.get("folderStructure"), "Folder Structure"),
        },
        {
            "title": "Database Documentation",
            "content": _normalize_content(generated_docs.get("database") or generated_docs.get("database_documentation"), "Database Documentation"),
        },
        {
            "title": "Security Findings",
            "content": "\n".join(["# Security Findings", "", "## Findings", *security_lines]),
        },
        {
            "title": "AI Recommendations",
            "content": "\n".join(["# AI Recommendations", "", *recommendation_lines]),
        },
        {
            "title": "Code Quality Metrics",
            "content": "\n".join(["# Code Quality Metrics", "", "## Quality Snapshot", *metrics_lines]),
        },
        {
            "title": "Knowledge Graph Summary",
            "content": "\n".join([
                "# Knowledge Graph Summary",
                "",
                "## Summary",
                "The knowledge graph captures entities, modules, dependencies, and architecture relationships automatically discovered from the repository analysis.",
                "",
                "## Notes",
                "- Expand the repository graph view in the application to inspect node-to-node relationships and dependency paths.",
                "- A complete graph view is useful for change impact analysis, onboarding, and architecture review.",
            ]),
        },
    ]
    return sections

# --- Main PDF Generator Function ---
def compile_report_pdf(
    project_name: str,
    project_owner: str,
    repository_source: str,
    commit_hash: str,
    sections: List[Dict[str, str]], # list of {"title": str, "content": str}
    output_path: str
):
    """
    Runs a 2-pass compilation:
    1. Pass 1 builds a PDF structure with a dummy/empty TOC page. The HeadingMarker objects
       register their final page numbers on the custom canvas.
    2. Pass 2 builds the final PDF, rendering a correct Table of Contents page using the recorded numbers.
    """
    headings_dict = {}
    
    # We define a function to construct the complete document story
    def build_story(recorded_pages: dict) -> List[Flowable]:
        parser = MarkdownPDFParser()
        story = []

        # ==========================================
        # 1. COVER PAGE
        # ==========================================
        story.append(Spacer(1, 40))
        
        # Banner Accent
        banner_style = TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#0f172a')), # Slate 900
            ('BOTTOMPADDING', (0,0), (-1,-1), 24),
            ('TOPPADDING', (0,0), (-1,-1), 24),
            ('LEFTPADDING', (0,0), (-1,-1), 24),
        ])
        
        title_style = ParagraphStyle(
            'CoverTitle',
            fontName='Helvetica-Bold',
            fontSize=30,
            leading=36,
            textColor=colors.white
        )
        
        title_para = Paragraph("CodeSphere AI", title_style)
        title_table = Table([[title_para]], colWidths=[504], style=banner_style)
        story.append(title_table)
        
        story.append(Spacer(1, 24))
        
        subtitle_style = ParagraphStyle(
            'CoverSubtitle',
            fontName='Helvetica',
            fontSize=16,
            leading=22,
            textColor=colors.HexColor('#3b82f6') # Blue 500
        )
        story.append(Paragraph("Enterprise Quality Repository Architecture & Audit Report", subtitle_style))
        story.append(Spacer(1, 100))

        # Metadata Section
        meta_label_style = ParagraphStyle('MetaL', fontName='Helvetica-Bold', fontSize=10, textColor=colors.HexColor('#64748b'))
        meta_val_style = ParagraphStyle('MetaV', fontName='Helvetica', fontSize=10, textColor=colors.HexColor('#0f172a'))
        
        meta_data = [
            [Paragraph("Project Name:", meta_label_style), Paragraph(project_name, meta_val_style)],
            [Paragraph("Owner:", meta_label_style), Paragraph(project_owner, meta_val_style)],
            [Paragraph("Source:", meta_label_style), Paragraph(repository_source, meta_val_style)],
            [Paragraph("Commit Hash:", meta_label_style), Paragraph(commit_hash or "N/A", meta_val_style)],
            [Paragraph("Generated:", meta_label_style), Paragraph(datetime.datetime.now().strftime("%B %d, %Y - %H:%M"), meta_val_style)],
        ]
        
        meta_table = Table(meta_data, colWidths=[100, 404], style=TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LINEBELOW', (0,0), (-1,-2), 0.5, colors.HexColor('#f1f5f9')),
        ]))
        story.append(meta_table)
        story.append(PageBreak())

        # ==========================================
        # 2. TABLE OF CONTENTS
        # ==========================================
        story.append(Paragraph("Table of Contents", parser.h1_style))
        story.append(Spacer(1, 15))
        
        toc_lines = []
        for index, s in enumerate(sections, 1):
            title = s["title"]
            page_num = str(recorded_pages.get(title, "..."))
            
            p_title = Paragraph(f"<b>{index}. {title}</b>", parser.body_style)
            p_page = Paragraph(f"<font color='#64748b'>Page {page_num}</font>", ParagraphStyle('TOCPage', parent=parser.body_style, alignment=2))
            toc_lines.append([p_title, p_page])
            
        toc_table = Table(toc_lines, colWidths=[400, 104], style=TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LINEBELOW', (0,0), (-1,-1), 0.5, colors.HexColor('#e2e8f0')),
        ]))
        story.append(toc_table)
        story.append(PageBreak())

        # ==========================================
        # 3. CHAPTERS
        # ==========================================
        for s in sections:
            title = s["title"]
            content = s["content"] or "No content generated for this section."
            
            # Make sure it starts with the expected H1 layout
            formatted_content = content
            if not content.strip().startswith("#"):
                formatted_content = f"# {title}\n\n{content}"
                
            story.extend(parser.parse(formatted_content))

        return story

    # --- PASS 1: Generate layout and record page numbers ---
    pass1_story = build_story(headings_dict)
    pass1_canvas_class = make_canvas_class(headings_dict)
    
    # We build into a temporary buffer or dummy path to record coordinates
    dummy_pdf_path = output_path + ".tmp"
    doc1 = SimpleDocTemplate(
        dummy_pdf_path,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    doc1.build(pass1_story, canvasmaker=pass1_canvas_class)
    
    # Clean up the draft file
    try:
        Path(dummy_pdf_path).unlink()
    except Exception:
        pass

    # --- PASS 2: Build the final document with actual TOC pages ---
    final_story = build_story(headings_dict)
    final_canvas_class = make_canvas_class(headings_dict)
    doc2 = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54
    )
    doc2.build(final_story, canvasmaker=final_canvas_class)
